apiVersion: v1
kind: Service
metadata:
  name: consulta-cnpj-service
  labels:
    app: consulta-cnpj-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: consulta-cnpj-service
  type: NodePort
